In [7]:
import numpy as np

In [87]:
#1 Odd Ones Out

In [21]:
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])

print(arr)


[[1 2 3]
 [5 7 9]
 [2 4 6]
 [7 7 7]]


In [25]:
arr[1, :]

array([5, 7, 9])

In [19]:
arr[3, :]

array([7, 7, 7])

In [64]:
#attempt #1
def onlyOdd(cluster_array):
    new_clusters_odd_only = []
    new_clusters_odd_only.append(arr[1, :])
    new_clusters_odd_only.append(arr[3, :])
    new_clusters_odd_only = np.reshape(new_clusters_odd_only, (2, 3))
    return new_clusters_odd_only

answer1 = onlyOdd(arr)
print(answer1)

[[5 7 9]
 [7 7 7]]


In [66]:
#attempt #2
def onlyOdd_test(cluster_array):
    new_clusters_odd_only = []
    for x in arr:
        for value in arr[x, :]:
            if value % 2 != 0:
                new_clusters_odd_only.append[x, :]
    return new_clusters_odd_only

answer1 = onlyOdd_test(arr)
print(answer1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [68]:
#attempt #3
def onlyOdd_test(cluster_array):
    new_clusters_odd_only = []
    for x in cluster_array[x, :]:
        if x.all() % 2 != 0:
            new_clusters_odd_only.append[x, :]
    return new_clusters_odd_only

answer1 = onlyOdd_test(arr)
print(answer1)

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [81]:
#attempt #3 (final attempt)
def onlyOdd_test(cluster_array):
    odd_rows = arr[np.all(cluster_array % 2 != 0, axis=1)] #axis=1 means to check if all the values in a row (column-wise, number by number) align with the condition given before
    return odd_rows

answer1 = onlyOdd_test(arr) #arr as in the array, not the function
print(answer1)

[[5 7 9]
 [7 7 7]]


In [ ]:
#2 Let's Play Checkers!

In [160]:
#2.1
checkerboard = np.zeros((8, 8), dtype='int16')
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [172]:
#2.2
checkerboard[0::2, 0::2] = 1 #every other row starting at the 0th row ("0::2"), every other number starting at the 0th index ("0::2")
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [174]:
#2.3
checkerboard[1::2, 1::2] = 1 #every other row starting at the 1st row ("1::2"), every other number starting at the 1st index ("1::2")
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [178]:
#2.4
reverse_checkerboard =  np.zeros((8, 8), dtype='int16')
reverse_checkerboard[0::2, 1::2] = 1 
reverse_checkerboard[1::2, 0::2] = 1
print(reverse_checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [232]:
#3 The Expanding Universe
#Test
space_str = '2' * 4
print(space_str)

print("_________________________")

#Test 2
test = np.str.join(' ', 'galaxy')
print(test)

2222
_________________________


/var/folders/yr/z3bmf_254gs6t4r3xpst1g3r0000gn/T/ipykernel_31049/4041328933.py:9: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  test = np.str.join(' ', 'galaxy')


AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [234]:
universe = np.array(['galaxy', 'clusters'])
print(universe)

def expansion(array_1, num_1):
    space_str = ' ' * num_1 
    #will return a string whose length depends on the value of num_1: if num_1 = 1, space_str = ' '; if num_1 = 5, space_str = '     '. 
    expanded_array_1 = np.char.join(space_str, array_1)
    #adds the space_str in between every character within the array_1: if num_1 = 1, expanded_array_1 = 'e x a m p l e' (with 1 space in between every letter of 'example')
    return expanded_array_1

expansion(universe, 1)

['galaxy' 'clusters']


array(['g a l a x y', 'c l u s t e r s'], dtype='<U15')

In [249]:
#4 
np.random.seed(42)
#for every time the command below is ran (w/ seed = 42), the "random" numbers will be the same because the seed is 42. like minecraft
planets = np.random.randint(100, 1000, size=(5, 5))
print(planets)

[[202 535 960 370 206]
 [171 800 120 714 221]
 [566 314 430 558 187]
 [472 199 971 763 230]
 [761 408 869 443 591]]


In [255]:
def secondLargest(array_2):
    #initialize an empty array to hold results
    second_largest_values_collection = np.empty(array.shape[1])
    